### ISSUE TITLE
shortcut when using MAT causes fail when autosim is provided

### ISSUE THREAD

**Issue by lukasjonkers** [richardjtelford/palaeoSig#2]
I think the speed-up for MAT in
https://github.com/richardjtelford/palaeoSig/blob/9b8634fe27afc35c94956911ad57dc5dd4f2b669/R/1_randomTF.R#L132-L139

causes a conflict when autosim is provided
https://github.com/richardjtelford/palaeoSig/blob/9b8634fe27afc35c94956911ad57dc5dd4f2b669/R/1_randomTF.R#L182-L184
because the dimensions of env (and spp) have changed.

Shouldn't the relevant rows in autosim be dropped too? Something like

```
if (identical(fun, MAT)) {
  mod1 <- predict(MAT(spp, env[[1]]), fos)
  analogues <- unique(as.vector(as.numeric(mod1$match.name)))
  spp <- spp[analogues, ]
  env <- env[analogues, , drop = FALSE]
  rownames(spp) <- seq_len(nrow(spp))
  if (!missing(autosim)) {
    autosim <- autosim[analogues, ]
  }
}
```

**Comment by richardjtelford** [comment]
Thanks - fixed. Please install from github as I cannot submit to CRAN at the moment (cannot install R v4 on this computer)
